mode: "wsup"
task: "codesearch"
gpu_ids: [0]
test_dataset: "python"
n_epochs: 10
learning_rate: 0.00001
lambda_cl: 1.0
lambda_bc: 0.2
contrastive_loss: "margin"
margin: 0.2
temperature: 1.0
anom_score: "softmax"
threshold: null

model:
  pretrained: True
  encoder: "microsoft/graphcodebert-base"
  task: "codesearch"
  num_features: 768
  dropout: 0.1
  num_classes: 2
  classifier: "dense"
  freeze_layers: null

dataset:
  name: "python"
  root: "./data/"
  mode: "wsup"
  batch_size: 64
  num_workers: 16
  code_col: "code"
  text_col: "text"
  url_col: "url"
  label_col: "label"
  tokenizer: "microsoft/graphcodebert-base"
  code_len: 256
  text_len: 128
  buggy_ratio: 0.01
  shuffle_ratio: 0.01
  wrong_text_ratio: 0.01
  out_domain_ratio: 0.01
  anom_test: 0.2